# .streamlit/config.toml

[theme]
primaryColor = "#1670B7"         
backgroundColor = "#F0F2F6"      
secondaryBackgroundColor = "#FFFFFF" 
textColor = "#303030"            
font = "sans serif"      

